#!/usr/bin/perl
#use the script as follows:
#./sub_3dpv 1 inpfile | qsub -N jobname

#@ARGV > 0 or die "usage: sub_3dpv nnodes inpfile|qsub -N jobname \n";
@ARGV > 0 or die "usage: sub_3dpv inpfile | qsub -N jobname \n";
#$n=$ARGV[0];
$n=1;
#$nprocs=$n*1;
#$inpfile=$ARGV[1];
$inpfile=$ARGV[0];
#This part creates necessary directories;
$execpath="/usr/local/bin/";
$fullpath="/home/nicola/ML/rruff-ir";
$basedir = $inpfile;
$basedir =~ s{\.[^.]+$}{};
$percvtest=5;
$percvtrain=100-$percvtest;
$inpfiletest=$basedir."_test-".$percvtest."pc.txt";
$inpfiletrain=$basedir."_train-".$percvtrain."pc.txt";

print "#!/bin/sh
#PBS -l nodes=$n:ppn=1
#PBS -N SLP

cat \$PBS_NODEFILE > \$PBS_O_WORKDIR/nodes.out

  cd $fullpath
  mkdir $basedir
  #$execpath/CrossValidMaker.py $inpfile $percvtest
  cp $inpfiletrain $basedir
  cp $inpfiletest $basedir
  cd $basedir
  $fullpath/SpectraLearnPredict.py -a $inpfiletrain $inpfiletest 2>&1 | tee -a log_$inpfile

";

